# docker-compose.yml

version: '3'

services:
  postgres:
    image: postgres:alpine
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: uala_events_postgres
      POSTGRES_USER: mjannello
      POSTGRES_PASSWORD: uala_db_password
    volumes:
      - ./migrations/postgres:/docker-entrypoint-initdb.d
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  command-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
