# docker-compose.yml

version: '3'

services:
  postgres:
    image: postgres:9.5
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: uala_events_postgres
      POSTGRES_USER: mjannello
      POSTGRES_PASSWORD: uala_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/postgres:/docker-entrypoint-initdb.d
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  command-app:
    build:
      context: .
      dockerfile: Dockerfile.command
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - rabbitmq
      - postgres
  query-app:
    build:
      context: .
      dockerfile: Dockerfile.query
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - rabbitmq
      - mongodb
      - command-app
volumes:
  postgres_data:
    driver: local
